name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Generate release notes from GitHub
        run: |
          mkdir ./tmp
          TAG_NAME=${GITHUB_REF#refs/tags/}
          (gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/releases/generate-notes \
            -f "tag_name=$TAG_NAME" -f "target_commitish=${{ github.sha }}") > ./tmp/release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --release-notes="./tmp/release.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
